name: eht-imaging
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - alsa-lib=1.2.3=h516909a_0
  - aom=3.3.0=h27087fc_1
  - astropy=5.0.2=py310hde88566_0
  - asttokens=2.0.5=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blosc=1.21.0=h9c3ff4c_0
  - brotli=1.0.9=h7f98852_6
  - brotli-bin=1.0.9=h7f98852_6
  - brotlipy=0.7.0=py310h6acc77f_1003
  - brunsli=0.1=h9c3ff4c_0
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - c-blosc2=2.0.4=h5f21a17_1
  - ca-certificates=2021.10.8=ha878542_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2021.10.8=py310hff52083_1
  - cffi=1.15.0=py310h0fdd8cc_0
  - cfitsio=4.0.0=h9a35b8e_0
  - charls=2.3.4=h9c3ff4c_0
  - charset-normalizer=2.0.12=pyhd8ed1ab_0
  - cloudpickle=2.0.0=pyhd8ed1ab_0
  - cryptography=36.0.2=py310h597c629_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cytoolz=0.11.2=py310h6acc77f_1
  - dask-core=2022.3.0=pyhd8ed1ab_0
  - dbus=1.13.6=h5008d03_3
  - decorator=5.1.1=pyhd8ed1ab_0
  - ephem=4.1.3=py310h6acc77f_2
  - executing=0.8.3=pyhd8ed1ab_0
  - expat=2.4.7=h27087fc_0
  - fftw=3.3.10=nompi_h77c792f_102
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.13.96=h8e229c2_2
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.31.2=py310h5764c6d_0
  - freetype=2.10.4=h0708190_1
  - fsspec=2022.2.0=pyhd8ed1ab_0
  - future=0.18.2=py310hff52083_4
  - gettext=0.19.8.1=h73d1719_1008
  - giflib=5.2.1=h36c2ea0_2
  - gst-plugins-base=1.20.1=hcf0ee16_1
  - gstreamer=1.20.1=hd4edc92_1
  - h5py=3.6.0=nompi_py310he751f51_100
  - hdf5=1.12.1=nompi_h2386368_104
  - icu=69.1=h9c3ff4c_0
  - idna=3.3=pyhd8ed1ab_0
  - imagecodecs=2022.2.22=py310h8534204_0
  - imageio=2.16.1=pyhcf75d05_0
  - importlib-metadata=4.11.3=py310hff52083_0
  - ipython=8.1.1=py310hff52083_0
  - jbig=2.1=h7f98852_2003
  - jedi=0.18.1=py310hff52083_0
  - jpeg=9e=h7f98852_0
  - jxrlib=1.1=h7f98852_2
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.0=py310hbf28c38_0
  - krb5=1.19.3=h3790be6_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libaec=1.0.6=h9c3ff4c_0
  - libavif=0.9.3=h166bdaf_1
  - libblas=3.9.0=13_linux64_openblas
  - libbrotlicommon=1.0.9=h7f98852_6
  - libbrotlidec=1.0.9=h7f98852_6
  - libbrotlienc=1.0.9=h7f98852_6
  - libcblas=3.9.0=13_linux64_openblas
  - libclang=13.0.1=default_hc23dcda_0
  - libcurl=7.82.0=h7bff187_0
  - libdeflate=1.10=h7f98852_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h9b69904_4
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=11.2.0=h1d223b6_14
  - libgfortran-ng=11.2.0=h69a702a_14
  - libgfortran5=11.2.0=h5c6108e_14
  - libglib=2.70.2=h174f98d_4
  - libgomp=11.2.0=h1d223b6_14
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=13_linux64_openblas
  - libllvm13=13.0.1=hf817b99_2
  - libnghttp2=1.47.0=h727a467_0
  - libnsl=2.0.0=h7f98852_0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.18=pthreads_h8fe5266_0
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.37=h21135ba_2
  - libpq=14.2=hd57d9b9_0
  - libssh2=1.10.0=ha56f1ee_2
  - libstdcxx-ng=11.2.0=he4da1e4_14
  - libtiff=4.3.0=h542a066_3
  - libuuid=2.32.1=h7f98852_1000
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp=1.2.2=h3452ae3_0
  - libwebp-base=1.2.2=h7f98852_1
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h885dcf4_1
  - libzlib=1.2.11=h36c2ea0_1013
  - libzopfli=1.0.3=h9c3ff4c_0
  - locket=0.2.0=py_2
  - lz4-c=1.9.3=h9c3ff4c_1
  - matplotlib=3.5.1=py310hff52083_0
  - matplotlib-base=3.5.1=py310h23f4a51_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.0.28=ha770c72_0
  - mysql-libs=8.0.28=hfa10184_0
  - ncurses=6.3=h9c3ff4c_0
  - networkx=2.7.1=pyhd8ed1ab_1
  - nfft=3.2.4=hf8c457e_1000
  - nspr=4.32=h9c3ff4c_1
  - nss=3.76=h2350873_0
  - numpy=1.22.3=py310h45f3432_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1n=h166bdaf_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.4.1=py310hb5077e9_0
  - parso=0.8.3=pyhd8ed1ab_0
  - partd=1.2.0=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.0.1=py310he619898_2
  - pip=22.0.4=pyhd8ed1ab_0
  - prompt-toolkit=3.0.27=pyha770c72_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyerfa=2.0.0.1=py310h96516ba_1
  - pygments=2.11.2=pyhd8ed1ab_0
  - pynfft=1.3.2=py310h96516ba_1004
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.7=pyhd8ed1ab_0
  - pyqt=5.12.3=py310hff52083_8
  - pyqt-impl=5.12.3=py310h1f8e252_8
  - pyqt5-sip=4.19.18=py310h122e73d_8
  - pyqtchart=5.12=py310hfcd6d55_8
  - pyqtwebengine=5.12.1=py310hfcd6d55_8
  - pysocks=1.7.1=py310hff52083_4
  - python=3.10.4=h9a8a25e_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytz=2022.1=pyhd8ed1ab_0
  - pywavelets=1.3.0=py310hde88566_0
  - pyyaml=6.0=py310h6acc77f_3
  - qt=5.12.9=h1304e3e_6
  - readline=8.1=h46c0cb4_0
  - requests=2.27.1=pyhd8ed1ab_0
  - scikit-image=0.19.2=py310hb5077e9_0
  - scipy=1.8.0=py310hea5193d_1
  - setuptools=60.10.0=py310hff52083_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.8=he1b5a44_3
  - sqlite=3.37.1=h4ff8645_0
  - stack_data=0.2.0=pyhd8ed1ab_0
  - tifffile=2022.3.16=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - toolz=0.11.2=pyhd8ed1ab_0
  - tornado=6.1=py310h6acc77f_2
  - traitlets=5.1.1=pyhd8ed1ab_0
  - tzdata=2022a=h191b570_0
  - unicodedata2=14.0.0=py310h6acc77f_0
  - urllib3=1.26.9=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.37.1=pyhd8ed1ab_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h7f98852_2
  - zfp=0.5.5=h9c3ff4c_8
  - zipp=3.7.0=pyhd8ed1ab_1
  - zlib=1.2.11=h36c2ea0_1013
  - zstd=1.5.2=ha95c52a_0
prefix: /home/sam/miniconda3/envs/eht-imaging
